### ISSUE TITLE
/var/run/cri-resmgr must be created before running cri-resmgr

### ISSUE THREAD

**Issue by mythi** [intel/cri-resource-manager#181] opened 2020-02-25 20:09 UTC
when launching `cri-resmgr` after a reboot, it fails to run

```
D: [   cri/server   ] waiting for server to become ready...                                                           
E: [   cri-resmgr   ] failed to start resource manager: resource-manager: failed to start configuration server: failed to listen to socket: listen unix /var/run/cri-resmgr/cri-resmgr-config.sock: bind: no such file or directory
```

but works after `sudo mkdir /var/run/cri-resmgr`.

**Comment by klihub** [comment] 2020-02-26 15:57
Hmm... I can't reproduce this, at least not without a reboot. I tried 'sudo rm -fr /var/run/cri-resmgr', then start cri-resmgr and it works. I'll try with a reboot but right now I don't see what could be the difference. Also considering that we have this in the code before socket creation/binding:

```
	if err := os.MkdirAll(filepath.Dir(s.options.Socket), 0700); err != nil {
		return serverError("failed to create directory for socket %s: %v",
			s.options.Socket, err)
	}
```

There was a recent bugfix affecting cri/server, but that was related to cri-resmgr not checking properly if another instance is already listening on the socket, removing the socket, and creating a new one instead of it. That was fixed by the #179 .

That said I don't see how this could be related, sans some really wierd and quirky timing problems and two competing cri-resmgr running... but event that way I don't see ATM how it could result in this. One part of the fixed bug was that cri-resmgr very generously gave the other, already running instance a full microsecond (!) to accept(2) a connect(2) attempt before deciding noone's home any more and taking over the socket.

**Comment by klihub** [comment] 2020-02-26 16:38
Hmm... I can reproduce this with a reboot.

**Comment by klihub** [comment] 2020-02-26 16:42
No, false alarm. I can't reproduce this at all.

**Comment by mythi** [comment] 2020-02-26 19:47
My command:
`sudo bin/cri-resmgr --runtime-socket /run/containerd/containerd.sock   -logger-debug all -logger-level debug -relay-socket /var/run/cri-resmgr.sock`

I'm at `c80aec2da619d76f0477c25253e752a7aea9697a`.

**Comment by klihub** [comment] 2020-02-27 09:08
Thanks, those exact params helped. I failed to spot in the error message that it's the *config* socket which fails. I think your trick that does it is to pick the socket path so that /var/lib/cri-resmgr does not get created. Also breaks saving/updating the cache AFAICT. Will fix that, too.

**Closed** 2020-02-28 09:04 UTC
